name: Terraform Azure VM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
  TF_VAR_admin_password: ${{ secrets.TF_VAR_admin_password }}
  # Provide ARM_* for Terraform provider from AZURE_CREDENTIALS JSON
  ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
  ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
  ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
  ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform -chdir=terraform init -input=false

      - name: Terraform Fmt (write)
        run: terraform -chdir=terraform fmt -recursive

      - name: Terraform Fmt (check)
        run: terraform -chdir=terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform -chdir=terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform -chdir=terraform plan -input=false -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform -chdir=terraform apply -input=false -auto-approve
